name: React CI/CD with Netlify

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '22.13.1'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v2.0.0
      with:
        publish-dir: ./dist   # if using Vite; use build/ for CRA
        production-deploy: true
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        # NETLIFY_SITE_ID: 25d6080c-a45b-4f6f-972f-643f563b9211
